### ISSUE TITLE
Scala and Finch example backend

### ISSUE THREAD

**Issue by adlawson** [shunterjs/example-backend-spec#1]
I think I've followed the spec as best I could.
The only differences are in the README because of the added compilation step and running from either source or build.

Let me know if you want me to fix something up or if you don't really want it.

https://github.com/adlawson/example-backend-scala-finch

**Comment by adlawson** [comment]
I hadn't noticed the tests in the spec but they showed I had missed the `application/x-shunter+json` content type. Should be fixed now.

```
  Example Back End
    Home
      ✓ Should respond with a 200 status
      ✓ Should respond with Shunter JSON
      ✓ Should respond with the expected JSON structure
    Venue
      ✓ Should respond with a 200 status
      ✓ Should respond with Shunter JSON
      ✓ Should respond with the expected JSON structure
    Venue image
      ✓ Should respond with a 200 status
      ✓ Should respond with a JPEG
      ✓ Should respond with the expected image data
    Random
      ✓ Should respond with a 302 status
      ✓ Should respond with a Location header that corresponds to a venue page
    404
      ✓ Should respond with a 404 status
```

**Comment by rowanmanning** [comment]
This looks awesome, and happy to host it under this org if you are. Change the owner and I'll add you as a team member :)

**Comment by adlawson** [comment]
All moved over :dancers:
